sudo: required
language: generic
services:
  - docker

before_install
  - docker build -t alexvinitsky/react-test -f ./client/Dockerfile.dev .     

script:
  - docker run -e CI=true alexvinitsky/react-test npm test -- --coverage  

after_sucess:
  - docker build -t alexvinitsky/multi-client ./client
  - docker build -t alexvinitsky/multi-nginx ./nginx
  - docker build -t alexvinitsky/multi-server ./server
  - docker build -t alexvinitsky/multi-worker ./worker
